export const HomeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "About me",
    headLine: "Introduction",
    description: "Hello my name is Mike van der Caaij and I'm 21 years old (turning 22 in July). Currently I'm still a student at Avans University of Applied Sciences and working towards becoming a Fullstack developer. Right now I'm really into programming with JavaScript. The reason I enjoy this language so much is because it has a lot of options for either Frontend or Backend.",
    buttonLabel: "Button",
    imgStart: false,
    img: require("../../images/svg-9.svg"),
    alt: "car",
    dark: true,
    primary: true,
    darkText: false,
    displayBtn: false,
    href: "/",
};

export const HomeObjTwo = {
    id: "projects",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: "Projects",
    headLine: "All of my projects",
    description: "Click on the button below to see all of my projects!",
    buttonLabel: "See my projects",
    imgStart: true,
    img: require("../../images/svg-6.svg"),
    alt: "project",
    dark: false,
    primary: false,
    darkText: true,
    href: "//github.com/mikevandercaaij",
    displayBtn: true,
    target: "_blank",
};

export const HomeObjThree = {
    id: "cv",
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "CV",
    headLine: "Curriculum Vitae",
    description: "If you've read all the information on this website and want to know read more about my past education/previous jobs, you can read my CV below!",
    buttonLabel: "Read CV",
    imgStart: false,
    img: require("../../images/svg-5.svg"),
    alt: "cv",
    dark: false,
    primary: false,
    darkText: true,
    href: "//www.mikevandercaaij.nl/img/cv.jpg",
    target: "_blank",
    displayBtn: true,
};
